import { getOpenRouterClient, toOpenRouterModel } from "@/lib/ai/openrouter"
import { toOpenAIMessages, toOpenAITools, type CompatTool } from "@/lib/ai/openrouter-message"

/**
 * Streaming model calls through OpenRouter.
 *
 * WHY THIS EXISTS. The first OpenRouter migration moved only the one-shot calls
 * (callAgent, createMessageCompat), and createMessageCompat says outright that it
 * does not stream. Everything that streamed — the program chat and the admin AI
 * chat among them — kept calling Anthropic directly, and with the Anthropic
 * account unfunded those answered "Your credit balance is too low".
 *
 * THE CONTRACT is the two Anthropic generators in functions/src/ai/anthropic.ts,
 * `streamRaw` and `streamWithTools`. These produce the SAME event shapes in the
 * SAME order, because the fallback wrapper swaps one for the other behind a
 * consumer that must not be able to tell which provider answered.
 *
 * Provider choice and the Anthropic fallback are NOT decided here. These
 * generators only speak to OpenRouter; the wrapper owns the fallback policy,
 * including the rule that a stream which has already emitted anything is never
 * replayed on the other provider.
 *
 * Twin: functions/src/ai/openrouter-stream.ts (generated by
 * scripts/gen-openrouter-twins.py — do not edit the twin by hand).
 */

export type OpenRouterToolStreamEvent =
  | { type: "text"; text: string }
  | { type: "tool_start"; name: string; label?: string }
  | { type: "tool_result"; name: string }
  | { type: "usage"; input_tokens: number; output_tokens: number }

export interface StreamSystemBlock {
  type: "text"
  text: string
  cache_control?: { type: "ephemeral" }
}

type StreamTextEvent = { type: "text"; text: string } | { type: "usage"; input_tokens: number; output_tokens: number }

type SimpleMessage = { role: "user" | "assistant"; content: string }

/**
 * One streamed chunk as OpenRouter sends it. Typed locally rather than with the
 * SDK's ChatCompletionChunk because OpenRouter adds two things OpenAI does not
 * have: a top-level `error` object, and `finish_reason: "error"`.
 */
interface OpenRouterChunk {
  choices?: Array<{
    delta?: {
      content?: string | null
      tool_calls?: Array<{
        index: number
        id?: string
        function?: { name?: string; arguments?: string }
      }>
    }
    finish_reason?: string | null
  }>
  usage?: { prompt_tokens?: number; completion_tokens?: number } | null
  error?: { code?: unknown; message?: string }
}

/** What one round of streaming has accumulated so far. */
export interface StreamRound {
  model: string
  round: number
  text: string
  /** Keyed by the tool call's `index`, which is the ONLY thing every delta for that call carries. */
  calls: Map<number, { id?: string; name?: string; arguments: string }>
  usage: { prompt_tokens: number; completion_tokens: number } | null
  /** The last finish_reason seen; "length" means max_tokens cut the round off. */
  finishReason: string | null
}

export function newStreamRound(model: string, round: number): StreamRound {
  return { model, round, text: "", calls: new Map(), usage: null, finishReason: null }
}

type FoldEvent = { type: "text"; text: string } | { type: "tool_start"; name: string }

function streamFailure(model: string, message: string, code: unknown, cause?: unknown): Error & { status?: number } {
  const err = new Error(
    `OpenRouter stream failed mid-response (model: ${model}): ${message}`,
    cause === undefined ? undefined : { cause },
  ) as Error & { status?: number }
  if (typeof code === "number") err.status = code
  return err
}

/**
 * Fold one chunk into the round, returning the events it makes visible.
 *
 * Tool calls are the fiddly part. OpenAI streams each call as a run of deltas
 * that share an `index`: the id and name arrive on the FIRST delta, the
 * arguments arrive as fragments across many later ones, and two calls' fragments
 * can interleave. Joining fragments by arrival order instead of by index is not
 * a type error — it produces `{"q":{}"x"}` and a parse failure that blames the
 * model.
 *
 * Some upstream providers repeat the name on later deltas for the same call. A
 * name is therefore taken once and never appended to, and `tool_start` fires
 * only when a call's name FIRST appears — once per call, as streamWithTools does
 * on `content_block_start`.
 */
export function foldStreamChunk(state: StreamRound, raw: unknown): FoldEvent[] {
  const chunk = (raw ?? {}) as OpenRouterChunk

  // OpenRouter has already answered 200 by the time a mid-stream fault happens,
  // so the real status exists only inside this chunk.
  if (chunk.error) {
    throw streamFailure(state.model, chunk.error.message ?? JSON.stringify(chunk.error), chunk.error.code)
  }

  // Usage is read before (and independently of) choices[0], because it arrives
  // in BOTH shapes: OpenAI's documented final chunk with an EMPTY `choices`,
  // and — measured live through OpenRouter — the chunk still carrying the
  // finish_reason. Gating on either shape reports 0 tokens for the other.
  if (chunk.usage) {
    state.usage = {
      prompt_tokens: chunk.usage.prompt_tokens ?? 0,
      completion_tokens: chunk.usage.completion_tokens ?? 0,
    }
  }

  const choice = chunk.choices?.[0]
  if (!choice) return []
  if (choice.finish_reason === "error") {
    throw streamFailure(state.model, 'finish_reason "error" with no error detail', undefined)
  }
  if (choice.finish_reason) state.finishReason = choice.finish_reason

  const events: FoldEvent[] = []
  const content = choice.delta?.content
  if (content) {
    state.text += content
    events.push({ type: "text", text: content })
  }

  for (const delta of choice.delta?.tool_calls ?? []) {
    let call = state.calls.get(delta.index)
    if (!call) {
      call = { arguments: "" }
      state.calls.set(delta.index, call)
    }
    if (delta.id && !call.id) call.id = delta.id
    if (delta.function?.name && !call.name) {
      call.name = delta.function.name
      events.push({ type: "tool_start", name: call.name })
    }
    if (delta.function?.arguments) call.arguments += delta.function.arguments
  }

  return events
}

interface CompletedToolCall {
  id: string
  name: string
  input: Record<string, unknown>
}

/**
 * The round's tool calls in call (index) order, arguments parsed.
 *
 * A call whose name never arrived is dropped, as createMessageCompat drops one.
 * A call whose arguments will not parse is an error rather than `{}`: an empty
 * object is indistinguishable from a legitimately argument-free call, and the
 * tool would run on input the model never sent.
 */
function completedToolCalls(state: StreamRound): CompletedToolCall[] {
  const out: CompletedToolCall[] = []
  for (const index of [...state.calls.keys()].sort((a, b) => a - b)) {
    const call = state.calls.get(index)!
    if (!call.name) continue
    let input: Record<string, unknown>
    try {
      input = JSON.parse(call.arguments || "{}")
    } catch {
      throw new Error(`Tool call "${call.name}" returned unparseable arguments (model: ${state.model})`)
    }
    // Round in the id because every round's ids share one conversation history;
    // `call_0` from round 1 and round 2 would collide.
    out.push({ id: call.id ?? `openrouter_call_r${state.round}_${index}`, name: call.name, input })
  }
  return out
}

/**
 * The openai SDK checks every SSE payload for `error` ITSELF and throws
 * `new APIError(undefined, data.error)` — status undefined, OpenRouter's number
 * only in `.code`. So a real mid-stream 502 never reaches foldStreamChunk's
 * error branch; it arrives here looking status-less, and shouldFallBackToAnthropic
 * treats a status-less error as our own bug and refuses to fall back. Lifting the
 * code onto `.status` keeps a provider fault classified as one.
 *
 * Exported because EVERY streamed OpenRouter request meets the same SDK
 * behaviour — callAgentViaOpenRouter and the page builder's object stream
 * included — and each must classify a mid-stream 502 the same way.
 */
export function liftStreamStatus(error: unknown, model: string): unknown {
  const e = error as { status?: unknown; code?: unknown; message?: unknown } | null
  if (!e || typeof e.status === "number" || typeof e.code !== "number") return error
  return streamFailure(model, typeof e.message === "string" ? e.message : String(error), e.code, error)
}

function callerAbort(model: string): Error {
  const err = new Error(`OpenRouter stream aborted by the caller (model: ${model})`)
  err.name = "AbortError"
  return err
}

function toSystemMessages(system: string | StreamSystemBlock[]): Array<Record<string, unknown>> {
  if (typeof system === "string") return system ? [{ role: "system", content: system }] : []
  if (system.length === 0) return []
  // ONE system message with one part per block. OpenRouter passes each part's
  // cache_control through to Anthropic, which is how the caller's cache
  // breakpoint keeps meaning what it meant — a plain string cannot carry one.
  return [
    {
      role: "system",
      content: system.map((b) => ({
        type: "text",
        text: b.text,
        ...(b.cache_control ? { cache_control: b.cache_control } : {}),
      })),
    },
  ]
}

/** Run one streamed request, folding each chunk into `state` and re-emitting what it yields. */
async function* streamRound(
  body: Record<string, unknown>,
  state: StreamRound,
  signal: AbortSignal | undefined,
): AsyncGenerator<FoldEvent> {
  const client = getOpenRouterClient()
  const stream = (await client.chat.completions.create(
    // include_usage is what makes OpenRouter send the usage chunk at all.
    { ...body, stream: true, stream_options: { include_usage: true } } as never,
    { signal },
  )) as unknown as AsyncIterable<unknown>

  try {
    for await (const chunk of stream) {
      // Chunks the SDK had already buffered keep arriving after the signal
      // fires — measured live, three more text deltas on Haiku. The caller has
      // stopped listening, so nothing further is emitted.
      if (signal?.aborted) break
      for (const event of foldStreamChunk(state, chunk)) yield event
    }
  } catch (e) {
    throw liftStreamStatus(e, state.model)
  }

  // The SDK's iterator RETURNS quietly when the signal fires, so an aborted
  // stream is otherwise indistinguishable from a finished one: half an answer,
  // a usage event, and a caller that stores it as the reply.
  if (signal?.aborted) throw callerAbort(state.model)
}

export async function* streamTextViaOpenRouter(opts: {
  model: string
  system: string | StreamSystemBlock[]
  messages: SimpleMessage[]
  maxTokens: number
  signal?: AbortSignal
}): AsyncGenerator<StreamTextEvent> {
  const state = newStreamRound(opts.model, 0)
  const body = {
    model: toOpenRouterModel(opts.model),
    max_tokens: opts.maxTokens,
    messages: [...toSystemMessages(opts.system), ...toOpenAIMessages(opts.messages)],
  }

  for await (const event of streamRound(body, state, opts.signal)) {
    if (event.type === "text") yield event
  }

  yield {
    type: "usage",
    input_tokens: state.usage?.prompt_tokens ?? 0,
    output_tokens: state.usage?.completion_tokens ?? 0,
  }
}

export async function* streamWithToolsViaOpenRouter(opts: {
  model: string
  system: StreamSystemBlock[]
  messages: SimpleMessage[]
  tools: CompatTool[]
  executeTool: (name: string, input: Record<string, unknown>) => Promise<string>
  toolLabels?: Record<string, string>
  maxTokens: number
  maxToolRounds: number
  signal?: AbortSignal
}): AsyncGenerator<OpenRouterToolStreamEvent> {
  const model = toOpenRouterModel(opts.model)
  const tools = toOpenAITools(opts.tools)
  let messages: Array<Record<string, unknown>> = [...toSystemMessages(opts.system), ...toOpenAIMessages(opts.messages)]

  // prompt_tokens ALREADY includes cached tokens (see normalizeUsage), so these
  // are read and summed, never topped up with a cache counter.
  let inputTokens = 0
  let outputTokens = 0

  for (let round = 0; round < opts.maxToolRounds; round++) {
    const state = newStreamRound(opts.model, round)

    for await (const event of streamRound({ model, max_tokens: opts.maxTokens, messages, tools }, state, opts.signal)) {
      if (event.type === "text") yield event
      else yield { type: "tool_start", name: event.name, label: opts.toolLabels?.[event.name] }
    }

    inputTokens += state.usage?.prompt_tokens ?? 0
    outputTokens += state.usage?.completion_tokens ?? 0

    // max_tokens ran out, possibly mid-way through a tool call's arguments.
    // streamWithTools ends on any stop_reason but "tool_use" and runs nothing,
    // so this does too — a budget cut is not the model sending malformed
    // arguments, and must not be reported as one.
    if (state.finishReason === "length") break

    const calls = completedToolCalls(state)
    if (calls.length === 0) break

    // As streamWithTools does, the tools of the LAST allowed round still run and
    // report even though no round follows to read their results: a consumer
    // that opened a spinner on tool_start is waiting for the tool_result.
    const results = await Promise.all(calls.map((c) => opts.executeTool(c.name, c.input)))
    for (const call of calls) yield { type: "tool_result", name: call.name }

    // Reassigned, never pushed: the array just sent belongs to that request.
    // Arguments are re-serialized from the parsed input rather than echoed raw,
    // because a no-argument call can stream "" — which is not JSON, and which
    // OpenRouter has to parse again to build Anthropic's tool_use block.
    messages = [
      ...messages,
      {
        role: "assistant",
        content: state.text || null,
        tool_calls: calls.map((c) => ({
          id: c.id,
          type: "function",
          function: { name: c.name, arguments: JSON.stringify(c.input) },
        })),
      },
      ...calls.map((c, i) => ({ role: "tool", tool_call_id: c.id, content: results[i] })),
    ]
  }

  yield { type: "usage", input_tokens: inputTokens, output_tokens: outputTokens }
}
