// Codegen script — FAQ CMS marketing-route registry
//
// Recursively scans app/(marketing)/ for page.tsx files, derives each route,
// filters out routes that should never have FAQs (home, dynamic segments,
// cart/checkout/orders, success pages, legal/utility pages), and writes the
// surviving routes to lib/faq/marketing-routes.generated.ts.
//
// Runtime fs scanning is not safe on Vercel serverless, so this runs at build
// time (wired into prebuild/predev) and the .generated.ts file is committed.
//
// Run: npx tsx scripts/generate-faq-pages.ts
import { readdirSync, writeFileSync } from "node:fs"
import { join, relative, sep } from "node:path"

const ROOT = process.cwd()
const MARKETING_DIR = join(ROOT, "app", "(marketing)")
const OUTPUT_FILE = join(ROOT, "lib", "faq", "marketing-routes.generated.ts")

// ─── Scan ───────────────────────────────────────────────────────────────────

/** Recursively collect absolute paths of files named exactly `page.tsx`. */
function findPageFiles(dir: string): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      out.push(...findPageFiles(full))
    } else if (entry.isFile() && entry.name === "page.tsx") {
      out.push(full)
    }
  }
  return out
}

/** Derive the URL route from an app/(marketing)/.../page.tsx file path. */
function routeFromPageFile(pageFile: string): string {
  // Path relative to app/(marketing), e.g. "services/online-vs-in-person/page.tsx"
  const rel = relative(MARKETING_DIR, pageFile)
  const segments = rel.split(sep).slice(0, -1) // drop trailing "page.tsx"
  // The (marketing) route group contributes nothing to the URL — it is already
  // stripped because we made the path relative to MARKETING_DIR.
  return segments.length === 0 ? "/" : "/" + segments.join("/")
}

// ─── Exclusions ─────────────────────────────────────────────────────────────

function isExcluded(route: string): boolean {
  // Home route never has FAQs.
  if (route === "/") return true

  const segments = route.split("/").filter(Boolean)

  // Any dynamic segment, e.g. [slug], [type], [sport], [orderNumber].
  if (segments.some((s) => s.startsWith("[") && s.endsWith("]"))) return true

  // Any `success` segment.
  if (segments.includes("success")) return true

  // Shop cart / checkout / orders subtrees.
  if (route === "/shop/cart" || route.startsWith("/shop/cart/")) return true
  if (route === "/shop/checkout" || route.startsWith("/shop/checkout/")) return true
  if (route === "/shop/orders" || route.startsWith("/shop/orders/")) return true

  // Exact utility / legal routes.
  const EXACT_EXCLUDED = new Set([
    "/coming-soon",
    "/unsubscribe",
    "/privacy-policy",
    "/terms-of-service",
  ])
  if (EXACT_EXCLUDED.has(route)) return true

  return false
}

// ─── Generate ───────────────────────────────────────────────────────────────

function main() {
  const pageFiles = findPageFiles(MARKETING_DIR)
  const routes = pageFiles
    .map(routeFromPageFile)
    .filter((route) => !isExcluded(route))
    .sort((a, b) => a.localeCompare(b))

  const header = `// AUTO-GENERATED by scripts/generate-faq-pages.ts — do not edit by hand`
  const body = routes.map((r) => `  ${JSON.stringify(r)},`).join("\n")
  const contents = `${header}\n\nexport const MARKETING_FAQ_ROUTES: readonly string[] = [\n${body}\n]\n`

  writeFileSync(OUTPUT_FILE, contents, "utf8")
  console.log(`✅ Wrote ${routes.length} marketing FAQ routes to lib/faq/marketing-routes.generated.ts`)
}

main()
